# Generated by Django 4.2.19 on 2025-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(
                default='review_default_jpg', null=True, upload_to='reviews/'
                ),
        ),
    ]
