# Generated by Django 4.2.19 on 2025-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review_caption_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
