# Generated by Django 4.2.19 on 2025-03-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='caption',
        ),
    ]
