# Generated by Django 4.2.19 on 2025-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa
                ('business_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('product_description', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exhibition Registration',
                'verbose_name_plural': 'Exhibition Registrations',
                'ordering': ['business_name'],
            },
        ),
    ]
