# Generated by Django 4.2.19 on 2025-03-10 10:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_exhibitionregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='image',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='exhibitionregistration',
            name='product_description',
            field=models.TextField(max_length=1000),
        ),
    ]
