# Generated by Django 4.2.19 on 2025-03-14 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_exhibitionregistration_product_registration_image'
         ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionregistration',
            name='product_registration_image',
        ),
        migrations.AddField(
            model_name='exhibitionregistration',
            name='registration_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Registration Date' # noqa
                ),
        ),
    ]
