# Generated by Django 4.2.19 on 2025-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'exhibition', '0005_remove_exhibitionregistration_product_registration_image_and_more' # noqa
            ),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionregistration',
            name='user_image',
            field=models.ImageField(
                blank=True, null=True, upload_to='exhibition_registrations/'
                ),
        ),
    ]
