# Generated by Django 4.2.19 on 2025-03-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_exhibitionregistration_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionregistration',
            name='user_image',
        ),
    ]
