# Generated by Django 4.2.19 on 2025-03-04 09:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_image',
            field=cloudinary.models.CloudinaryField(
                default='placeholder', max_length=255, verbose_name='image'
                ),
        ),
    ]
