# Generated by Django 4.2.19 on 2025-03-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_review_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='caption',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
